buildscript {
 repositories { maven { url = 'https://maven.minecraftforge.net' }; mavenCentral() }
 dependencies { classpath 'net.minecraftforge.gradle:ForgeGradle:3.0.197' }
}
apply plugin: 'net.minecraftforge.gradle'
version = '1.0.0'
group = 'de.skyz.pipacrafthud'
archivesBaseName = 'PiPaCraftHUD'
sourceCompatibility = targetCompatibility = '1.8'
tasks.withType(JavaCompile) { options.encoding = 'UTF-8' }
minecraft { mappings channel: 'stable', version: '39-1.12' }
dependencies { minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2859' }
task hudTests(type: JavaExec, dependsOn: testClasses) {
 main = 'de.skyz.pipacrafthud.HudTextTest'
 classpath = sourceSets.test.runtimeClasspath
}
check.dependsOn hudTests
jar.finalizedBy('reobfJar')
